#!/usr/bin/env python3
"""Apply a routing plan (JSON) to a KiCad project: net classes, net-class
patterns, board minimum rules, predefined track/via sizes, and custom DRC rules.

Pure Python - edits the .kicad_pro (JSON) and .kicad_dru (S-expr text) next to
the board. Does NOT need pcbnew, so it can run anywhere. CLOSE THE PROJECT IN
KICAD FIRST, otherwise KiCad overwrites these files on its next save.

Usage:
  apply_constraints.py plan.json path/to/board.kicad_pcb [--dry-run]
  apply_constraints.py --list-fabs

Plan format: see templates/routing_plan.example.json and SKILL.md Phase 3.
Everything this tool owns in .kicad_dru lives between
'# BEGIN kicad-routing' / '# END kicad-routing' - your hand-written rules
outside that block are preserved.
"""
from __future__ import annotations

import argparse
import copy
import json
import re
import shutil
import sys
from pathlib import Path

# Conservative "design-to" minimums (mm). ALWAYS confirm on the fab's current
# capabilities page - limits change and cheaper tiers differ from the absolute minimum.
FAB_PRESETS = {
    "generic_conservative": dict(min_track_width=0.15, min_clearance=0.15, min_via_diameter=0.6,
                                 min_through_hole_diameter=0.3, min_via_annular_width=0.15,
                                 min_hole_to_hole=0.5, min_hole_clearance=0.25,
                                 min_copper_edge_clearance=0.4),
    "jlcpcb_2layer": dict(min_track_width=0.127, min_clearance=0.127, min_via_diameter=0.6,
                          min_through_hole_diameter=0.3, min_via_annular_width=0.15,
                          min_hole_to_hole=0.5, min_hole_clearance=0.25,
                          min_copper_edge_clearance=0.3),
    "jlcpcb_4layer": dict(min_track_width=0.1, min_clearance=0.1, min_via_diameter=0.45,
                          min_through_hole_diameter=0.2, min_via_annular_width=0.125,
                          min_hole_to_hole=0.5, min_hole_clearance=0.2,
                          min_copper_edge_clearance=0.3),
    "pcbway_standard": dict(min_track_width=0.15, min_clearance=0.15, min_via_diameter=0.6,
                            min_through_hole_diameter=0.3, min_via_annular_width=0.15,
                            min_hole_to_hole=0.5, min_hole_clearance=0.25,
                            min_copper_edge_clearance=0.3),
    "oshpark_2layer": dict(min_track_width=0.1524, min_clearance=0.1524, min_via_diameter=0.508,
                           min_through_hole_diameter=0.254, min_via_annular_width=0.127,
                           min_hole_to_hole=0.5, min_hole_clearance=0.2,
                           min_copper_edge_clearance=0.381),
    "oshpark_4layer": dict(min_track_width=0.127, min_clearance=0.127, min_via_diameter=0.457,
                           min_through_hole_diameter=0.254, min_via_annular_width=0.1016,
                           min_hole_to_hole=0.5, min_hole_clearance=0.2,
                           min_copper_edge_clearance=0.381),
}

NETCLASS_FIELDS_MM = ["clearance", "track_width", "via_diameter", "via_drill",
                      "microvia_diameter", "microvia_drill",
                      "diff_pair_width", "diff_pair_gap", "diff_pair_via_gap"]

BEGIN, END = "# BEGIN kicad-routing (generated by apply_constraints.py)", "# END kicad-routing"


def die(msg):
    sys.exit("ERROR: " + msg)


# ---------------------------------------------------------------- validation
def validate(plan, rules):
    errs, warns = [], []
    names = set()
    for nc in plan.get("netclasses", []):
        n = nc.get("name")
        if not n:
            errs.append("netclass without name")
            continue
        if n in names:
            errs.append(f"duplicate netclass {n}")
        names.add(n)
        tw, cl = nc.get("track_width"), nc.get("clearance")
        if tw is not None and tw < rules["min_track_width"]:
            errs.append(f"{n}: track_width {tw} < fab min {rules['min_track_width']}")
        if cl is not None and cl < rules["min_clearance"]:
            errs.append(f"{n}: clearance {cl} < fab min {rules['min_clearance']}")
        vd, vr = nc.get("via_diameter"), nc.get("via_drill")
        if vd is not None and vr is not None:
            ring = (vd - vr) / 2
            if ring < rules["min_via_annular_width"] - 1e-9:
                errs.append(f"{n}: via annular ring {ring:.3f} < fab min {rules['min_via_annular_width']}")
            if vr < rules["min_through_hole_diameter"] - 1e-9:
                errs.append(f"{n}: via drill {vr} < fab min {rules['min_through_hole_diameter']}")
        if nc.get("diff_pair_width") and not nc.get("diff_pair_gap"):
            warns.append(f"{n}: diff_pair_width set without diff_pair_gap")
        if nc.get("current_a") and tw:
            # cheap IPC-2221 external 1oz 10C check
            need = ((nc["current_a"] / (0.048 * 10 ** 0.44)) ** (1 / 0.725)) / (plan.get("copper_oz", 1) * 1.378) / 39.37
            if tw + 1e-9 < need:
                errs.append(f"{n}: track_width {tw} mm too thin for {nc['current_a']} A "
                            f"(IPC-2221 ext/10C needs >= {need:.2f} mm; run trace_width.py)")
        if not (nc.get("patterns") or nc.get("nets")) and n != "Default":
            warns.append(f"{n}: no patterns/nets - class will be empty")
    for dp in plan.get("diff_pairs", []):
        if dp.get("netclass") and dp["netclass"] not in names:
            errs.append(f"diff pair {dp.get('name')} refers to unknown netclass {dp['netclass']}")
    return errs, warns


# ---------------------------------------------------------------- .kicad_pro
def apply_project(pro, plan, rules):
    ns = pro.setdefault("net_settings", {})
    classes = ns.setdefault("classes", [])
    by_name = {c.get("name"): c for c in classes}
    default = by_name.get("Default")
    if default is None:
        default = {"name": "Default", "clearance": 0.2, "track_width": 0.25, "via_diameter": 0.6,
                   "via_drill": 0.3, "microvia_diameter": 0.3, "microvia_drill": 0.1,
                   "diff_pair_width": 0.2, "diff_pair_gap": 0.25, "diff_pair_via_gap": 0.25,
                   "bus_width": 12, "wire_width": 6, "line_style": 0,
                   "pcb_color": "rgba(0, 0, 0, 0.000)", "schematic_color": "rgba(0, 0, 0, 0.000)",
                   "priority": 2147483647}
        classes.insert(0, default)
        by_name["Default"] = default

    changes = []
    for i, nc in enumerate(plan.get("netclasses", [])):
        name = nc["name"]
        target = by_name.get(name)
        if target is None:
            target = copy.deepcopy(default)
            target["name"] = name
            target["priority"] = nc.get("priority", i)
            classes.append(target)
            by_name[name] = target
            changes.append(f"netclass + {name}")
        else:
            changes.append(f"netclass ~ {name}")
        for f in NETCLASS_FIELDS_MM:
            if nc.get(f) is not None:
                target[f] = float(nc[f])
        if "priority" in nc and name != "Default":
            target["priority"] = nc["priority"]

    # patterns: drop old patterns that point at classes we manage, then add ours
    managed = {nc["name"] for nc in plan.get("netclasses", [])}
    pats = [p for p in ns.get("netclass_patterns") or [] if p.get("netclass") not in managed]
    for nc in plan.get("netclasses", []):
        for pat in nc.get("patterns", []) + nc.get("nets", []):
            pats.append({"netclass": nc["name"], "pattern": pat})
    ns["netclass_patterns"] = pats

    # board minimum rules + predefined sizes
    ds = pro.setdefault("board", {}).setdefault("design_settings", {})
    r = ds.setdefault("rules", {})
    for k, v in rules.items():
        r[k] = float(v)
    widths = sorted({float(nc["track_width"]) for nc in plan.get("netclasses", []) if nc.get("track_width")})
    if widths:
        ds["track_widths"] = [0.0] + widths
    vias = sorted({(float(nc["via_diameter"]), float(nc["via_drill"]))
                   for nc in plan.get("netclasses", []) if nc.get("via_diameter") and nc.get("via_drill")})
    if vias:
        ds["via_dimensions"] = [{"diameter": 0.0, "drill": 0.0}] + [{"diameter": d, "drill": h} for d, h in vias]
    dps = sorted({(float(nc["diff_pair_width"]), float(nc.get("diff_pair_gap", 0)), float(nc.get("diff_pair_via_gap", nc.get("diff_pair_gap", 0))))
                  for nc in plan.get("netclasses", []) if nc.get("diff_pair_width")})
    if dps:
        ds["diff_pair_dimensions"] = [{"gap": 0.0, "via_gap": 0.0, "width": 0.0}] + \
            [{"gap": g, "via_gap": vg, "width": w} for w, g, vg in dps]
    return changes


# ---------------------------------------------------------------- .kicad_dru
def q(s):
    return s.replace("'", "\\'")


def dru_rules(plan):
    out = []
    for dp in plan.get("diff_pairs", []):
        name, base = dp["name"], dp.get("match", dp.get("base"))
        if not base:
            continue
        cond = f"A.inDiffPair('{q(base)}')"
        if dp.get("max_skew_mm") is not None:
            out.append(f'(rule "{name} skew"\n  (condition "{cond}")\n  (constraint skew (max {dp["max_skew_mm"]}mm)))')
        if dp.get("max_uncoupled_mm") is not None:
            out.append(f'(rule "{name} uncoupled"\n  (condition "{cond}")\n  (constraint diff_pair_uncoupled (max {dp["max_uncoupled_mm"]}mm)))')
        if dp.get("gap_mm") is not None:
            out.append(f'(rule "{name} gap"\n  (condition "{cond}")\n  (constraint diff_pair_gap (min {dp["gap_mm"] * 0.9:.4f}mm) (opt {dp["gap_mm"]}mm) (max {dp["gap_mm"] * 1.1:.4f}mm)))')
        if dp.get("max_vias") is not None:
            out.append(f'(rule "{name} via count"\n  (condition "{cond}")\n  (constraint via_count (max {dp["max_vias"]})))')
        if dp.get("max_length_mm") is not None:
            out.append(f'(rule "{name} length"\n  (condition "{cond}")\n  (constraint length (max {dp["max_length_mm"]}mm)))')
    for g in plan.get("length_groups", []):
        cond = g.get("condition") or f"A.hasNetclass('{q(g['netclass'])}')"
        parts = []
        if g.get("min_mm") is not None:
            parts.append(f"(min {g['min_mm']}mm)")
        if g.get("max_mm") is not None:
            parts.append(f"(max {g['max_mm']}mm)")
        if parts:
            out.append(f'(rule "{g["name"]} length"\n  (condition "{cond}")\n  (constraint length {" ".join(parts)}))')
        if g.get("max_skew_mm") is not None:
            out.append(f'(rule "{g["name"]} skew"\n  (condition "{cond}")\n  (constraint skew (max {g["max_skew_mm"]}mm)))')
    for k in plan.get("keepaways", []):
        # extra clearance between a noisy net and everything else (e.g. SMPS switch node)
        out.append(f'(rule "{k["name"]}"\n  (condition "A.NetName == \'{q(k["net"])}\' && B.NetName != \'{q(k["net"])}\'")\n'
                   f'  (constraint clearance (min {k["clearance_mm"]}mm)))')
    for raw in plan.get("custom_rules", []):
        out.append(raw.strip())
    return out


def apply_dru(dru_path: Path, rules):
    text = dru_path.read_text(encoding="utf-8") if dru_path.exists() else ""
    text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S)
    if "(version" not in text:
        text = "(version 1)\n" + text
    if rules:
        block = BEGIN + "\n" + "\n\n".join(rules) + "\n" + END + "\n"
        text = text.rstrip() + "\n\n" + block
    return text


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("plan", nargs="?")
    ap.add_argument("board", nargs="?")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true", help="apply even if validation fails")
    ap.add_argument("--list-fabs", action="store_true")
    a = ap.parse_args()

    if a.list_fabs:
        print(json.dumps(FAB_PRESETS, indent=2))
        return
    if not (a.plan and a.board):
        ap.error("plan and board are required")

    plan = json.loads(Path(a.plan).read_text(encoding="utf-8"))
    board = Path(a.board)
    pro_path, dru_path = board.with_suffix(".kicad_pro"), board.with_suffix(".kicad_dru")
    if not pro_path.exists():
        die(f"{pro_path} not found - constraints live in the project file next to the board")
    lock = board.parent / ("~" + board.name + ".lck")
    if lock.exists():
        print(f"WARNING: {lock.name} exists - close the board in KiCad or it will overwrite these edits.")

    fab = plan.get("fab", "generic_conservative")
    if isinstance(fab, str):
        if fab not in FAB_PRESETS:
            die(f"unknown fab preset '{fab}'. Options: {', '.join(FAB_PRESETS)}")
        rules = dict(FAB_PRESETS[fab])
    else:
        rules = dict(FAB_PRESETS["generic_conservative"], **fab)
    rules.update(plan.get("fab_overrides", {}))

    errs, warns = validate(plan, rules)
    for w in warns:
        print("warn:", w)
    for e in errs:
        print("ERROR:", e)
    if errs and not a.force:
        sys.exit(1)

    pro = json.loads(pro_path.read_text(encoding="utf-8"))
    changes = apply_project(pro, plan, rules)
    dru_text = apply_dru(dru_path, dru_rules(plan))

    print("board rules:", json.dumps(rules))
    print("\n".join(changes))
    print(f"{len(pro['net_settings']['netclass_patterns'])} netclass patterns")
    if a.dry_run:
        print("---- .kicad_dru preview ----\n" + dru_text)
        return
    shutil.copy2(pro_path, pro_path.with_suffix(".kicad_pro.bak"))
    pro_path.write_text(json.dumps(pro, indent=2) + "\n", encoding="utf-8")
    dru_path.write_text(dru_text, encoding="utf-8")
    print(f"wrote {pro_path.name} (backup .kicad_pro.bak) and {dru_path.name}")
    print("NEXT: re-open in KiCad or run DRC to confirm the rules parse (bad .kicad_dru syntax = DRC error).")


if __name__ == "__main__":
    main()
